package pkg

var RUNS_BEFORE_INCREASING_BACKTRACK_LIMIT_MAX = 300
var RUNS_BEFORE_INCREASING_BACKTRACK_LIMIT_MIN = 32
var DECREASE_RATE_FOR_RUNS_THRESHOLD = 0.95 //[0, 1]

var VAR_BRANCHING_ORDER_SHUFFLE_DISTANCE = 0.7 //[0, 1]
var VAR_BRANCHING_ORDER_SHUFFLE_CHANCE = 50    //[0, 100]

var DEPTH_LIFETIME_FOR_SORTING_ORDERS = 50

var BACKTRACK_LIMIT_MIN = 500

var BACKTRACK_LIMIT_INCREMENT_MIN = 1000
var BACKTRACK_LIMIT_INCREMENT_INCREASE_RATE = 1.05
